N2_VOCAB = [
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「促進」の意味として正しいものはどれですか。",
        "option_a": "物事が進むように働きかけること",
        "option_b": "物事を止めること",
        "option_c": "物事を記録すること",
        "option_d": "物事を比較すること",
        "correct_answer": "A",
        "explanation": "「促進」は物事が進むよう促すことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「維持」の意味として正しいものはどれですか。",
        "option_a": "新しく作ること",
        "option_b": "現状をそのまま保つこと",
        "option_c": "大きく変えること",
        "option_d": "完全になくすこと",
        "correct_answer": "B",
        "explanation": "「維持」は現状を保ち続けることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「構成」の意味として正しいものはどれですか。",
        "option_a": "いくつかの要素を組み合わせてまとまりを作ること",
        "option_b": "ものを壊すこと",
        "option_c": "情報を収集すること",
        "option_d": "問題を解決すること",
        "correct_answer": "A",
        "explanation": "「構成」は複数の要素を組み合わせて一つの全体を作ることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「傾向」の意味として正しいものはどれですか。",
        "option_a": "物事が一定の方向に向かう性質",
        "option_b": "まったく変化しない状態",
        "option_c": "突然起こる出来事",
        "option_d": "正確な数値や量",
        "correct_answer": "A",
        "explanation": "「傾向」は物事がある方向に偏りやすい性質を指す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「背景」の意味として正しいものはどれですか。",
        "option_a": "物事の前面に見えるもの",
        "option_b": "物事の後ろにある状況や事情",
        "option_c": "物事の将来の計画",
        "option_d": "物事の正確な定義",
        "correct_answer": "B",
        "explanation": "「背景」はある出来事や状況の裏にある事情や環境を指す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「概要」の意味として正しいものはどれですか。",
        "option_a": "詳細な説明",
        "option_b": "内容の大まかなあらまし",
        "option_c": "正確な数値データ",
        "option_d": "最終的な結論",
        "correct_answer": "B",
        "explanation": "「概要」は物事の大体の内容をまとめたものを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「具体的」の反対の意味を持つ言葉はどれですか。",
        "option_a": "現実的",
        "option_b": "抽象的",
        "option_c": "客観的",
        "option_d": "積極的",
        "correct_answer": "B",
        "explanation": "「具体的」の反対語は「抽象的」で、はっきりした形のない概念的なものを指す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「抽象的」の意味として正しいものはどれですか。",
        "option_a": "誰でも分かるほど分かりやすいこと",
        "option_b": "実体がなく概念的であること",
        "option_c": "非常に詳しいこと",
        "option_d": "感情的であること",
        "correct_answer": "B",
        "explanation": "「抽象的」は具体的な形や実体がなく、概念として捉えられることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「客観的」の意味として正しいものはどれですか。",
        "option_a": "個人の感情や意見に基づいていること",
        "option_b": "個人の感情を交えず事実に基づいていること",
        "option_c": "多くの人が知っていること",
        "option_d": "目標に向かって積極的に行動すること",
        "correct_answer": "B",
        "explanation": "「客観的」は自分の感情や主観を除いて物事を見ることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「慣用句」の意味として正しいものはどれですか。",
        "option_a": "新しく作られた言葉",
        "option_b": "慣習的に使われる決まった意味の言い回し",
        "option_c": "外国語から取り入れた言葉",
        "option_d": "専門的な技術用語",
        "correct_answer": "B",
        "explanation": "「慣用句」は習慣的に使われ、特定の意味を持つ言葉の組み合わせを指す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「影響」の意味として正しいものはどれですか。",
        "option_a": "他に作用を及ぼすこと",
        "option_b": "他と比較すること",
        "option_c": "他を模倣すること",
        "option_d": "他を排除すること",
        "correct_answer": "A",
        "explanation": "「影響」はある物事が別の物事に何らかの作用を与えることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「貢献」の意味として正しいものはどれですか。",
        "option_a": "社会や他者の役に立つために力を尽くすこと",
        "option_b": "自分だけの利益を追求すること",
        "option_c": "他者の行動を批判すること",
        "option_d": "責任を他者に押しつけること",
        "correct_answer": "A",
        "explanation": "「貢献」は社会や他の人のために役立つことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「把握」の意味として正しいものはどれですか。",
        "option_a": "物事をしっかり理解して掌握すること",
        "option_b": "物事を無視すること",
        "option_c": "物事を記録すること",
        "option_d": "物事を変更すること",
        "correct_answer": "A",
        "explanation": "「把握」は状況や内容をしっかりと理解・掌握することを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「妥当」の意味として正しいものはどれですか。",
        "option_a": "程度や内容が適切でふさわしいこと",
        "option_b": "非常に優れていること",
        "option_c": "普通よりも劣っていること",
        "option_d": "珍しくて貴重なこと",
        "correct_answer": "A",
        "explanation": "「妥当」は判断や処置が適切で道理にかなっていることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「矛盾」の意味として正しいものはどれですか。",
        "option_a": "二つの事柄が食い違って両立しないこと",
        "option_b": "二つの事柄がぴったり合うこと",
        "option_c": "一つの問題が解決されること",
        "option_d": "複数の意見が一致すること",
        "correct_answer": "A",
        "explanation": "「矛盾」は前後の事柄が食い違い、論理的に両立しないことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「効率」の意味として正しいものはどれですか。",
        "option_a": "使った労力に対して得られる成果の割合",
        "option_b": "仕事の難易度",
        "option_c": "作業にかかる合計時間",
        "option_d": "チームの人数",
        "correct_answer": "A",
        "explanation": "「効率」は投入した労力や資源に対する成果の比率を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「批判」の意味として正しいものはどれですか。",
        "option_a": "物事の良い点だけを評価すること",
        "option_b": "物事の誤りや問題点を指摘して論じること",
        "option_c": "物事を深く研究すること",
        "option_d": "物事を分かりやすく説明すること",
        "correct_answer": "B",
        "explanation": "「批判」は物事の欠点や問題点を取り上げて論じることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「前提」の意味として正しいものはどれですか。",
        "option_a": "議論や行動の出発点となる条件や仮定",
        "option_b": "議論の最終的な結論",
        "option_c": "過去に起きた出来事",
        "option_d": "将来の目標",
        "correct_answer": "A",
        "explanation": "「前提」は推論や議論の基礎となる条件や仮定を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「柔軟」の意味として正しいものはどれですか。",
        "option_a": "状況に応じてうまく対応できること",
        "option_b": "一つのやり方に固執すること",
        "option_c": "非常に強い力を持つこと",
        "option_d": "感情的に振る舞うこと",
        "correct_answer": "A",
        "explanation": "「柔軟」は状況の変化に応じて適切に対応できる性質を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「根拠」の意味として正しいものはどれですか。",
        "option_a": "判断や意見の基礎となる事実や理由",
        "option_b": "最終的な結論",
        "option_c": "将来の計画",
        "option_d": "過去の失敗",
        "correct_answer": "A",
        "explanation": "「根拠」は主張や判断を支える事実・理由・証拠を意味する。",
        "source_url": "",
        "passage": "",
    },
]

N2_GRAMMAR = [
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "彼の行動は会社の方針（　）ものだった。",
        "option_a": "に反した",
        "option_b": "に基づいた",
        "option_c": "を踏まえた",
        "option_d": "に際した",
        "correct_answer": "A",
        "explanation": "「〜に反して」は期待や規則に逆らっていることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "市場の調査結果（　）、新しい商品を開発することにした。",
        "option_a": "に反して",
        "option_b": "を踏まえて",
        "option_c": "にもかかわらず",
        "option_d": "どころか",
        "correct_answer": "B",
        "explanation": "「〜を踏まえて」はある事実や状況を考慮した上で行動することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "この研究は最新のデータ（　）進められている。",
        "option_a": "に際して",
        "option_b": "ばかりか",
        "option_c": "に基づいて",
        "option_d": "どころか",
        "correct_answer": "C",
        "explanation": "「〜に基づいて」はある基準や根拠に従って行動することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "大雨（　）、試合は予定通り行われた。",
        "option_a": "を踏まえて",
        "option_b": "に基づいて",
        "option_c": "にもかかわらず",
        "option_d": "に反して",
        "correct_answer": "C",
        "explanation": "「〜にもかかわらず」は逆接を表し、予想に反して別の結果になることを示す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "彼女は英語（　）フランス語も話せる。",
        "option_a": "どころか",
        "option_b": "ばかりか",
        "option_c": "に反して",
        "option_d": "に際して",
        "correct_answer": "B",
        "explanation": "「〜ばかりか」は一つのことに加えてさらに別のことも成立することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "彼はお礼を言う（　）、文句まで言い出した。",
        "option_a": "ばかりか",
        "option_b": "にもかかわらず",
        "option_c": "どころか",
        "option_d": "を踏まえて",
        "correct_answer": "C",
        "explanation": "「〜どころか」はある事柄が全く当てはまらず、むしろ逆の状況であることを強調する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "出発（　）、もう一度荷物を確認してください。",
        "option_a": "に基づいて",
        "option_b": "に際して",
        "option_c": "を踏まえて",
        "option_d": "ばかりか",
        "correct_answer": "B",
        "explanation": "「〜に際して」は重要な場面や時点において行動することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "彼の意見は常識（　）発言だと感じた。",
        "option_a": "を踏まえた",
        "option_b": "に基づいた",
        "option_c": "に反した",
        "option_d": "に際した",
        "correct_answer": "C",
        "explanation": "「〜に反した」は一般的な期待や常識に反することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "今回の経験（　）、次のプロジェクトを計画したい。",
        "option_a": "を踏まえて",
        "option_b": "にもかかわらず",
        "option_c": "どころか",
        "option_d": "ばかりか",
        "correct_answer": "A",
        "explanation": "「〜を踏まえて」は過去の経験や情報を参考にして次の行動を決めることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "この法律は憲法（　）制定されている。",
        "option_a": "どころか",
        "option_b": "に反して",
        "option_c": "に基づいて",
        "option_d": "ばかりか",
        "correct_answer": "C",
        "explanation": "「〜に基づいて」はある基準や原則に従って物事が行われることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "疲れている（　）、彼女は残業を引き受けた。",
        "option_a": "どころか",
        "option_b": "ばかりか",
        "option_c": "に際して",
        "option_d": "にもかかわらず",
        "correct_answer": "D",
        "explanation": "「〜にもかかわらず」は不利な状況にありながらも別の行動をとることを示す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "この製品は安い（　）品質も優れている。",
        "option_a": "にもかかわらず",
        "option_b": "に反して",
        "option_c": "ばかりか",
        "option_d": "に基づいて",
        "correct_answer": "C",
        "explanation": "「〜ばかりか」は一つの優れた点に加えてさらに別の良い点もあることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "入学（　）必要な書類を揃えてください。",
        "option_a": "に反して",
        "option_b": "に際して",
        "option_c": "どころか",
        "option_d": "を踏まえて",
        "correct_answer": "B",
        "explanation": "「〜に際して」はある重要な機会や時点に合わせて準備することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "彼は謝る（　）、さらに問題を起こした。",
        "option_a": "ばかりか",
        "option_b": "に基づいて",
        "option_c": "どころか",
        "option_d": "を踏まえて",
        "correct_answer": "C",
        "explanation": "「〜どころか」は予想とは全く逆の、より否定的な状況を強調する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "アンケートの結果（　）サービスを改善します。",
        "option_a": "にもかかわらず",
        "option_b": "に反して",
        "option_c": "に際して",
        "option_d": "に基づいて",
        "correct_answer": "D",
        "explanation": "「〜に基づいて」は収集したデータや事実を根拠として行動することを表す。",
        "source_url": "",
        "passage": "",
    },
]

N2_READING = [
    # Passage 1
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "この文章の主なテーマは何ですか。",
        "option_a": "環境問題と経済成長の両立",
        "option_b": "再生可能エネルギーの技術的な課題",
        "option_c": "化石燃料の将来性",
        "option_d": "国際的なエネルギー価格の変動",
        "correct_answer": "A",
        "explanation": "文章全体が環境保護と経済発展を同時に実現する可能性について論じている。",
        "source_url": "",
        "passage": "近年、環境問題への関心が高まる中、経済成長と環境保護の両立が重要な課題となっている。再生可能エネルギーの普及により、温室効果ガスの排出を抑えながら経済を発展させることが可能になってきた。しかし、初期投資の大きさや技術的な課題も残っており、政府や企業の継続的な取り組みが求められている。持続可能な社会を実現するためには、個人・企業・政府が一体となって行動する必要がある。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "再生可能エネルギーの普及によって何が可能になりましたか。",
        "option_a": "化石燃料の完全な廃止",
        "option_b": "温室効果ガスを抑えながら経済を発展させること",
        "option_c": "初期投資コストの完全な解消",
        "option_d": "政府の役割の縮小",
        "correct_answer": "B",
        "explanation": "文章は再生可能エネルギーが排出を抑えつつ経済発展を可能にすると述べている。",
        "source_url": "",
        "passage": "近年、環境問題への関心が高まる中、経済成長と環境保護の両立が重要な課題となっている。再生可能エネルギーの普及により、温室効果ガスの排出を抑えながら経済を発展させることが可能になってきた。しかし、初期投資の大きさや技術的な課題も残っており、政府や企業の継続的な取り組みが求められている。持続可能な社会を実現するためには、個人・企業・政府が一体となって行動する必要がある。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "文章によると、どのような課題が残っていますか。",
        "option_a": "初期投資の大きさと技術的な課題",
        "option_b": "環境問題への無関心",
        "option_c": "経済成長の停滞",
        "option_d": "再生可能エネルギーの需要不足",
        "correct_answer": "A",
        "explanation": "文章は「初期投資の大きさや技術的な課題も残っており」と明示している。",
        "source_url": "",
        "passage": "近年、環境問題への関心が高まる中、経済成長と環境保護の両立が重要な課題となっている。再生可能エネルギーの普及により、温室効果ガスの排出を抑えながら経済を発展させることが可能になってきた。しかし、初期投資の大きさや技術的な課題も残っており、政府や企業の継続的な取り組みが求められている。持続可能な社会を実現するためには、個人・企業・政府が一体となって行動する必要がある。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "持続可能な社会を実現するために必要なことは何ですか。",
        "option_a": "政府だけが取り組むこと",
        "option_b": "企業の利益を最優先すること",
        "option_c": "個人・企業・政府が一体となって行動すること",
        "option_d": "技術開発を中止すること",
        "correct_answer": "C",
        "explanation": "文章の最後に「個人・企業・政府が一体となって行動する必要がある」と述べられている。",
        "source_url": "",
        "passage": "近年、環境問題への関心が高まる中、経済成長と環境保護の両立が重要な課題となっている。再生可能エネルギーの普及により、温室効果ガスの排出を抑えながら経済を発展させることが可能になってきた。しかし、初期投資の大きさや技術的な課題も残っており、政府や企業の継続的な取り組みが求められている。持続可能な社会を実現するためには、個人・企業・政府が一体となって行動する必要がある。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "「継続的な取り組み」が求められているのは誰ですか。",
        "option_a": "研究者と学生",
        "option_b": "政府や企業",
        "option_c": "外国の機関",
        "option_d": "地域のボランティア",
        "correct_answer": "B",
        "explanation": "文章は「政府や企業の継続的な取り組みが求められている」と述べている。",
        "source_url": "",
        "passage": "近年、環境問題への関心が高まる中、経済成長と環境保護の両立が重要な課題となっている。再生可能エネルギーの普及により、温室効果ガスの排出を抑えながら経済を発展させることが可能になってきた。しかし、初期投資の大きさや技術的な課題も残っており、政府や企業の継続的な取り組みが求められている。持続可能な社会を実現するためには、個人・企業・政府が一体となって行動する必要がある。",
    },
    # Passage 2
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "この文章が最も伝えたいことは何ですか。",
        "option_a": "読書は時間の無駄である",
        "option_b": "読書習慣が思考力や語彙力の向上に役立つ",
        "option_c": "電子書籍は紙の本より優れている",
        "option_d": "学校教育では読書を教えるべきではない",
        "correct_answer": "B",
        "explanation": "文章は読書が思考力・語彙力・共感力を高める効果について説明している。",
        "source_url": "",
        "passage": "読書は単なる娯楽にとどまらず、思考力や語彙力を高める効果があると言われている。多様な文章に触れることで、論理的に考える力が自然と身につく。また、小説などのフィクションを読むことで他者の視点を理解し、共感する力も養われる。忙しい現代人にとって読書の時間を確保するのは難しいが、毎日少しずつ読む習慣をつけることが大切だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "フィクションを読むことでどのような力が養われますか。",
        "option_a": "計算能力",
        "option_b": "体力",
        "option_c": "他者の視点を理解し共感する力",
        "option_d": "記憶力",
        "correct_answer": "C",
        "explanation": "文章は「フィクションを読むことで他者の視点を理解し、共感する力も養われる」と述べている。",
        "source_url": "",
        "passage": "読書は単なる娯楽にとどまらず、思考力や語彙力を高める効果があると言われている。多様な文章に触れることで、論理的に考える力が自然と身につく。また、小説などのフィクションを読むことで他者の視点を理解し、共感する力も養われる。忙しい現代人にとって読書の時間を確保するのは難しいが、毎日少しずつ読む習慣をつけることが大切だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "現代人にとって読書のどのような点が難しいですか。",
        "option_a": "本の値段が高いこと",
        "option_b": "読書の時間を確保すること",
        "option_c": "本を見つけること",
        "option_d": "読書の内容を理解すること",
        "correct_answer": "B",
        "explanation": "文章は「忙しい現代人にとって読書の時間を確保するのは難しい」と述べている。",
        "source_url": "",
        "passage": "読書は単なる娯楽にとどまらず、思考力や語彙力を高める効果があると言われている。多様な文章に触れることで、論理的に考える力が自然と身につく。また、小説などのフィクションを読むことで他者の視点を理解し、共感する力も養われる。忙しい現代人にとって読書の時間を確保するのは難しいが、毎日少しずつ読む習慣をつけることが大切だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "多様な文章に触れることでどのような力が身につきますか。",
        "option_a": "外国語を話す力",
        "option_b": "論理的に考える力",
        "option_c": "素早く行動する力",
        "option_d": "数字を扱う力",
        "correct_answer": "B",
        "explanation": "文章は「多様な文章に触れることで、論理的に考える力が自然と身につく」と述べている。",
        "source_url": "",
        "passage": "読書は単なる娯楽にとどまらず、思考力や語彙力を高める効果があると言われている。多様な文章に触れることで、論理的に考える力が自然と身につく。また、小説などのフィクションを読むことで他者の視点を理解し、共感する力も養われる。忙しい現代人にとって読書の時間を確保するのは難しいが、毎日少しずつ読む習慣をつけることが大切だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "文章が勧める読書の方法はどれですか。",
        "option_a": "週末にまとめて長時間読む",
        "option_b": "毎日少しずつ読む習慣をつける",
        "option_c": "専門書だけを読む",
        "option_d": "音読で本を読む",
        "correct_answer": "B",
        "explanation": "文章は「毎日少しずつ読む習慣をつけることが大切だ」と勧めている。",
        "source_url": "",
        "passage": "読書は単なる娯楽にとどまらず、思考力や語彙力を高める効果があると言われている。多様な文章に触れることで、論理的に考える力が自然と身につく。また、小説などのフィクションを読むことで他者の視点を理解し、共感する力も養われる。忙しい現代人にとって読書の時間を確保するのは難しいが、毎日少しずつ読む習慣をつけることが大切だ。",
    },
]

N2_LISTENING = [
    {
        "level": "N2",
        "question_type": "listening",
        "question_text": "二人は何について話していますか。",
        "option_a": "週末の旅行計画",
        "option_b": "会議の準備と資料の確認",
        "option_c": "新しい社員の採用",
        "option_d": "来月の予算について",
        "correct_answer": "B",
        "explanation": "会話は明日の会議に向けた資料確認と準備について話している。",
        "source_url": "",
        "passage": "男性：明日の会議の資料、もう確認しましたか。\n女性：はい、一通り見ました。でも、3ページ目のグラフが少し分かりにくいかもしれません。\n男性：そうですか。修正しておきます。他に気になる点はありますか。\n女性：いいえ、それ以外は大丈夫だと思います。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "question_text": "女性は何が問題だと言っていますか。",
        "option_a": "資料全体が分かりにくい",
        "option_b": "3ページ目のグラフが分かりにくい",
        "option_c": "会議の日程が間違っている",
        "option_d": "資料のページ数が足りない",
        "correct_answer": "B",
        "explanation": "女性は「3ページ目のグラフが少し分かりにくいかもしれません」と述べている。",
        "source_url": "",
        "passage": "男性：明日の会議の資料、もう確認しましたか。\n女性：はい、一通り見ました。でも、3ページ目のグラフが少し分かりにくいかもしれません。\n男性：そうですか。修正しておきます。他に気になる点はありますか。\n女性：いいえ、それ以外は大丈夫だと思います。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "question_text": "男性はこの後何をしますか。",
        "option_a": "新しい資料を作る",
        "option_b": "会議を延期する",
        "option_c": "グラフを修正する",
        "option_d": "女性に連絡する",
        "correct_answer": "C",
        "explanation": "男性は「修正しておきます」と言ったのでグラフを直すことが分かる。",
        "source_url": "",
        "passage": "男性：明日の会議の資料、もう確認しましたか。\n女性：はい、一通り見ました。でも、3ページ目のグラフが少し分かりにくいかもしれません。\n男性：そうですか。修正しておきます。他に気になる点はありますか。\n女性：いいえ、それ以外は大丈夫だと思います。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "question_text": "女性が店員に最初に聞いたことは何ですか。",
        "option_a": "商品の値段",
        "option_b": "この商品が別の色で売っているかどうか",
        "option_c": "商品の返品方法",
        "option_d": "商品の使い方",
        "correct_answer": "B",
        "explanation": "女性は最初に「別の色はありますか」と色の種類について尋ねている。",
        "source_url": "",
        "passage": "女性：すみません、このバッグ、別の色はありますか。\n店員：はい、黒と紺がございます。こちらの青以外でよろしければご案内できます。\n女性：では、黒を見せてもらえますか。\n店員：少々お待ちください。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "question_text": "この店ではどの色のバッグが買えますか。",
        "option_a": "青・黒・紺",
        "option_b": "赤・青・黒",
        "option_c": "黒・白・紺",
        "option_d": "青・赤・白",
        "correct_answer": "A",
        "explanation": "会話から、青・黒・紺の三色が存在することが分かる。",
        "source_url": "",
        "passage": "女性：すみません、このバッグ、別の色はありますか。\n店員：はい、黒と紺がございます。こちらの青以外でよろしければご案内できます。\n女性：では、黒を見せてもらえますか。\n店員：少々お待ちください。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "question_text": "女性は最終的にどうしましたか。",
        "option_a": "青いバッグを買った",
        "option_b": "黒いバッグを見せてもらうことにした",
        "option_c": "何も買わずに帰った",
        "option_d": "紺のバッグを注文した",
        "correct_answer": "B",
        "explanation": "女性は「黒を見せてもらえますか」と言い、黒を確認することにした。",
        "source_url": "",
        "passage": "女性：すみません、このバッグ、別の色はありますか。\n店員：はい、黒と紺がございます。こちらの青以外でよろしければご案内できます。\n女性：では、黒を見せてもらえますか。\n店員：少々お待ちください。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "question_text": "二人は何について話していますか。",
        "option_a": "レポートの締め切りと提出方法",
        "option_b": "授業の時間割の変更",
        "option_c": "試験の結果",
        "option_d": "図書館の利用方法",
        "correct_answer": "A",
        "explanation": "会話はレポートの締め切りと提出方法について確認している。",
        "source_url": "",
        "passage": "学生A：来週のレポート、メールで提出していいですか。\n学生B：先生が印刷して出すように言っていたよ。\n学生A：そうか、知らなかった。締め切りはいつまでだっけ。\n学生B：金曜日の授業が終わるまでだって。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "question_text": "レポートの締め切りはいつですか。",
        "option_a": "来週の月曜日",
        "option_b": "金曜日の授業が終わるまで",
        "option_c": "今週の水曜日",
        "option_d": "メールで送った時点",
        "correct_answer": "B",
        "explanation": "学生Bが「金曜日の授業が終わるまでだって」と述べている。",
        "source_url": "",
        "passage": "学生A：来週のレポート、メールで提出していいですか。\n学生B：先生が印刷して出すように言っていたよ。\n学生A：そうか、知らなかった。締め切りはいつまでだっけ。\n学生B：金曜日の授業が終わるまでだって。",
    },
]


def get_n2_questions() -> list[dict]:
    return N2_VOCAB + N2_GRAMMAR + N2_READING + N2_LISTENING
