# JLPT N1 Practice Questions
# Total: 53 questions (20 vocab + 15 grammar + 10 reading + 8 listening)

N1_VOCAB = [
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「懸隔」の意味として最も適切なものはどれですか。",
        "option_a": "大きな隔たり・差異",
        "option_b": "強い執着",
        "option_c": "急激な変化",
        "option_d": "深い理解",
        "correct_answer": "A",
        "explanation": "「懸隔」は二つの物事の間に大きな差や隔たりがあることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「蔑視」の意味として最も適切なものはどれですか。",
        "option_a": "過度な賞賛",
        "option_b": "見下すこと・軽蔑",
        "option_c": "注意深く観察すること",
        "option_d": "感情を抑えること",
        "correct_answer": "B",
        "explanation": "「蔑視」は他者を見下し、軽蔑することを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「峻別」の意味として最も適切なものはどれですか。",
        "option_a": "曖昧に扱うこと",
        "option_b": "厳しく区別すること",
        "option_c": "徐々に近づくこと",
        "option_d": "深く反省すること",
        "correct_answer": "B",
        "explanation": "「峻別」は物事をきっぱりと厳しく区別することを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「措辞」の意味として最も適切なものはどれですか。",
        "option_a": "言葉の選び方・表現",
        "option_b": "文章の長さ",
        "option_c": "話す速度",
        "option_d": "声の大きさ",
        "correct_answer": "A",
        "explanation": "「措辞」は言葉の使い方や表現の仕方を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「憂慮」の意味として最も適切なものはどれですか。",
        "option_a": "喜びに満ちること",
        "option_b": "心配・気にかけること",
        "option_c": "怒りを感じること",
        "option_d": "驚くこと",
        "correct_answer": "B",
        "explanation": "「憂慮」は将来のことを心配し、気にかけることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「憤慨」の意味として最も適切なものはどれですか。",
        "option_a": "ひどく腹を立てること",
        "option_b": "深く悲しむこと",
        "option_c": "強く喜ぶこと",
        "option_d": "静かに考えること",
        "correct_answer": "A",
        "explanation": "「憤慨」は非常に腹を立て、憤ることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「陳腐」の意味として最も適切なものはどれですか。",
        "option_a": "新しくて珍しい",
        "option_b": "古くさくてつまらない",
        "option_c": "複雑で難解な",
        "option_d": "清潔で整った",
        "correct_answer": "B",
        "explanation": "「陳腐」は古くさくて平凡、目新しさのない様子を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「漸進」の意味として最も適切なものはどれですか。",
        "option_a": "急に後退すること",
        "option_b": "少しずつ前進すること",
        "option_c": "大きく飛躍すること",
        "option_d": "静止したままでいること",
        "correct_answer": "B",
        "explanation": "「漸進」は段階を追って少しずつ進んでいくことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「斟酌」の意味として最も適切なものはどれですか。",
        "option_a": "相手の事情を考慮して手加減すること",
        "option_b": "厳しく批判すること",
        "option_c": "無視して進むこと",
        "option_d": "強引に主張すること",
        "correct_answer": "A",
        "explanation": "「斟酌」は相手の立場や事情を考慮し、適切に対処することを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「諦観」の意味として最も適切なものはどれですか。",
        "option_a": "執念深く追いかけること",
        "option_b": "物事の本質を見極め、あきらめて達観すること",
        "option_c": "楽観的に将来を見ること",
        "option_d": "細部にこだわること",
        "correct_answer": "B",
        "explanation": "「諦観」は物事の本質を悟り、執着を捨てて落ち着いた境地に至ることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「逡巡」と最も近い意味の言葉はどれですか。",
        "option_a": "即断",
        "option_b": "躊躇",
        "option_c": "邁進",
        "option_d": "果断",
        "correct_answer": "B",
        "explanation": "「逡巡」はためらい、ぐずぐずすることで「躊躇」と意味が近い。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「僭越」の意味として最も適切なものはどれですか。",
        "option_a": "自分の立場を超えて出すぎること",
        "option_b": "謙虚に振る舞うこと",
        "option_c": "礼儀正しくすること",
        "option_d": "適切な範囲で行動すること",
        "correct_answer": "A",
        "explanation": "「僭越」は身分や立場をわきまえず、出すぎた行為をすることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「瞥見」の意味として最も適切なものはどれですか。",
        "option_a": "じっくり観察すること",
        "option_b": "ちらりと見ること",
        "option_c": "繰り返し確認すること",
        "option_d": "意図的に無視すること",
        "correct_answer": "B",
        "explanation": "「瞥見」はちらりと一瞬だけ見ることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「敷衍」の意味として最も適切なものはどれですか。",
        "option_a": "考えを簡潔にまとめること",
        "option_b": "意味を広げて詳しく説明すること",
        "option_c": "結論を急ぐこと",
        "option_d": "議論を打ち切ること",
        "correct_answer": "B",
        "explanation": "「敷衍」はある事柄をさらに広げて、詳しく説き明かすことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「矜持」の意味として最も適切なものはどれですか。",
        "option_a": "恥ずかしさ",
        "option_b": "自分の能力に対する誇り・プライド",
        "option_c": "他者への嫉妬",
        "option_d": "過度な謙遜",
        "correct_answer": "B",
        "explanation": "「矜持」は自分の能力や行動に対して持つ誇りやプライドを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「牽強付会」の意味として最も適切なものはどれですか。",
        "option_a": "道理に合った論理的な説明",
        "option_b": "道理に合わないことを無理に引きつけて解釈すること",
        "option_c": "複数の意見を公平にまとめること",
        "option_d": "専門家の意見に従うこと",
        "correct_answer": "B",
        "explanation": "「牽強付会」は自分に都合よく道理を曲げて解釈することを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「嚆矢」の意味として最も適切なものはどれですか。",
        "option_a": "物事の終わり",
        "option_b": "物事の始まり・最初",
        "option_c": "最も重要な部分",
        "option_d": "最も困難な段階",
        "correct_answer": "B",
        "explanation": "「嚆矢」は物事の始まりや先駆けとなるものを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「捨象」の意味として最も適切なものはどれですか。",
        "option_a": "不要な要素を取り除いて本質のみ抽出すること",
        "option_b": "具体的な例を多く挙げること",
        "option_c": "全体を俯瞰して見ること",
        "option_d": "細部を丁寧に分析すること",
        "correct_answer": "A",
        "explanation": "「捨象」は本質に関係しない要素を除いて、必要な性質のみを取り出すことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「闊達」の意味として最も適切なものはどれですか。",
        "option_a": "心が狭く偏っている",
        "option_b": "心が広くのびのびしている",
        "option_c": "慎重で用心深い",
        "option_d": "感情的で激しい",
        "correct_answer": "B",
        "explanation": "「闊達」は心が広く、小さなことにこだわらないおおらかな様子を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "vocabulary",
        "question_text": "「忌憚」を使った「忌憚のない意見」の意味として最も適切なものはどれですか。",
        "option_a": "遠慮や気遣いのない率直な意見",
        "option_b": "専門的な知識に基づいた意見",
        "option_c": "慎重に吟味された意見",
        "option_d": "多数の人が支持する意見",
        "correct_answer": "A",
        "explanation": "「忌憚のない」は遠慮や遠まわしな表現を省いた、率直で正直な様子を意味する。",
        "source_url": "",
        "passage": "",
    },
]

N1_GRAMMAR = [
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "本日（　　）をもちまして、当店は閉店いたします。",
        "option_a": "これ",
        "option_b": "それ",
        "option_c": "あれ",
        "option_d": "どれ",
        "correct_answer": "A",
        "explanation": "「これをもって」は「これによって・この時点で」という意味の改まった表現。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "この技術は熟練した職人（　　）ならではの繊細な作業だ。",
        "option_a": "に",
        "option_b": "で",
        "option_c": "を",
        "option_d": "が",
        "correct_answer": "A",
        "explanation": "「〜ならでは」はその人・物にしかできないことを表し、「〜に」と接続することが多い。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "彼女の努力（　　）もさることながら、才能も並外れている。",
        "option_a": "に",
        "option_b": "が",
        "option_c": "も",
        "option_d": "を",
        "correct_answer": "C",
        "explanation": "「〜もさることながら」は「〜はもちろんのこと、それ以上に」という意味で「〜も」と接続する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "周囲の反対（　　）をよそに、彼はプロジェクトを強行した。",
        "option_a": "の声",
        "option_b": "に関して",
        "option_c": "についても",
        "option_d": "のために",
        "correct_answer": "A",
        "explanation": "「〜をよそに」は「〜を無視して・〜に無関係に」という意味で、名詞に接続する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "受験シーズン（　　）とあって、図書館は朝から満員だった。",
        "option_a": "だ",
        "option_b": "に",
        "option_c": "で",
        "option_d": "を",
        "correct_answer": "A",
        "explanation": "「〜とあって」は「〜という状況なので」という理由を表し、名詞・動詞普通形などに「だ」を挟まず直接接続する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "部長（　　）ともなれば、部下の失敗にも責任を負わなければならない。",
        "option_a": "に",
        "option_b": "が",
        "option_c": "を",
        "option_d": "で",
        "correct_answer": "A",
        "explanation": "「〜ともなれば」は「〜という立場・段階になると当然」という意味で「〜に」と接続する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "あの映画を見て、涙を流さ（　　）ずにはいられなかった。",
        "option_a": "ず",
        "option_b": "れ",
        "option_c": "い",
        "option_d": "な",
        "correct_answer": "A",
        "explanation": "「〜ずにはいられない」は「〜せずにいられない・思わず〜してしまう」という意味。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "長年の研究の末、ついに新薬の開発に成功した。これを（　　）もって、報告といたします。",
        "option_a": "もち",
        "option_b": "もつ",
        "option_c": "もて",
        "option_d": "もった",
        "correct_answer": "A",
        "explanation": "「〜をもって」の「もって」は「持つ」の連用形で、手段・時点を表す改まった表現。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "この地方（　　）ならではの食文化を後世に伝えることが大切だ。",
        "option_a": "に",
        "option_b": "が",
        "option_c": "の",
        "option_d": "で",
        "correct_answer": "A",
        "explanation": "「〜ならでは」は「〜にしかない独自の」という意味で、「〜に」と接続する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "彼のプレゼンは内容（　　）もさることながら、話し方も非常に上手かった。",
        "option_a": "も",
        "option_b": "が",
        "option_c": "を",
        "option_d": "に",
        "correct_answer": "A",
        "explanation": "「〜もさることながら」の前には「〜も」が必要で、「内容も」と接続する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "家族の心配（　　）をよそに、彼女は危険な山岳登山を敢行した。",
        "option_a": "と",
        "option_b": "に",
        "option_c": "を",
        "option_d": "の",
        "correct_answer": "A",
        "explanation": "「〜をよそに」の前は名詞が来るが、この問題では文脈上「と」は不適切で「を」が助詞として正しい形が問われている。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "彼女は親友の裏切りを知り、怒りを隠さ（　　）にはいられなかった。",
        "option_a": "ず",
        "option_b": "ない",
        "option_c": "なく",
        "option_d": "ぬ",
        "correct_answer": "A",
        "explanation": "「〜ずにはいられない」は動詞未然形＋「ずにはいられない」の形を取る。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "新入社員（　　）とあって、彼はすべての仕事に全力で取り組んでいる。",
        "option_a": "だけ",
        "option_b": "ばかり",
        "option_c": "のみ",
        "option_d": "だ",
        "correct_answer": "D",
        "explanation": "「〜とあって」は「〜だとあって」の形で名詞に接続し、「〜という状況なので」を表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "一国の首相（　　）ともなれば、その言動が世界に影響を与える。",
        "option_a": "に",
        "option_b": "を",
        "option_c": "が",
        "option_d": "で",
        "correct_answer": "A",
        "explanation": "「〜ともなれば」は「〜になると」という意味で、地位・立場を示す名詞に「に」で接続する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N1",
        "question_type": "grammar",
        "question_text": "彼の誠意ある謝罪に、許さ（　　）ずにはいられない気持ちになった。",
        "option_a": "ない",
        "option_b": "ず",
        "option_c": "なく",
        "option_d": "れ",
        "correct_answer": "B",
        "explanation": "「〜ずにはいられない」は「許す」の未然形「許さ」に「ず」を付けた形が正しい。",
        "source_url": "",
        "passage": "",
    },
]

N1_READING = [
    # Passage 1: Philosophy of language (5 questions)
    {
        "level": "N1",
        "question_type": "reading",
        "question_text": "第一段落で筆者が主張していることはどれですか。",
        "option_a": "言語は思考を完全に反映する",
        "option_b": "言語は思考を制限することがある",
        "option_c": "言語がなければ思考は不可能だ",
        "option_d": "言語と思考は無関係だ",
        "correct_answer": "B",
        "explanation": "筆者は言語の構造が思考の枠組みを規定し、制限する側面があると述べている。",
        "source_url": "",
        "passage": "言語は単なる伝達の道具ではない。人が思考する際、言語はその枠組みそのものを形成する。ある概念を表す言葉が存在しない言語の話者は、その概念を認識しにくいという研究がある。例えば、色の区別を細かく持つ言語の話者は、そうでない言語の話者より色の識別が得意とされる。これは、言語が思考を助けるだけでなく、時に制限することも示している。",
    },
    {
        "level": "N1",
        "question_type": "reading",
        "question_text": "「色の区別」の例が示すことは何ですか。",
        "option_a": "色覚は人種によって異なる",
        "option_b": "言語の語彙が認知に影響する",
        "option_c": "視覚は言語より優れている",
        "option_d": "科学的な実験が重要だ",
        "correct_answer": "B",
        "explanation": "色彩語彙の多さが知覚に影響するという例は、言語の語彙体系が認知能力に影響することを示す。",
        "source_url": "",
        "passage": "言語は単なる伝達の道具ではない。人が思考する際、言語はその枠組みそのものを形成する。ある概念を表す言葉が存在しない言語の話者は、その概念を認識しにくいという研究がある。例えば、色の区別を細かく持つ言語の話者は、そうでない言語の話者より色の識別が得意とされる。これは、言語が思考を助けるだけでなく、時に制限することも示している。",
    },
    {
        "level": "N1",
        "question_type": "reading",
        "question_text": "この文章のテーマとして最も適切なものはどれですか。",
        "option_a": "言語学習の効果的な方法",
        "option_b": "言語と認知の相互関係",
        "option_c": "多言語話者の優位性",
        "option_d": "色彩感覚の文化的差異",
        "correct_answer": "B",
        "explanation": "文章全体を通じて、言語が思考・認知にどう影響するかが論じられている。",
        "source_url": "",
        "passage": "言語は単なる伝達の道具ではない。人が思考する際、言語はその枠組みそのものを形成する。ある概念を表す言葉が存在しない言語の話者は、その概念を認識しにくいという研究がある。例えば、色の区別を細かく持つ言語の話者は、そうでない言語の話者より色の識別が得意とされる。これは、言語が思考を助けるだけでなく、時に制限することも示している。",
    },
    {
        "level": "N1",
        "question_type": "reading",
        "question_text": "「言語が思考を制限する」とはどういう意味ですか。",
        "option_a": "言語を使うと頭が疲れる",
        "option_b": "語彙のない概念は認識されにくい",
        "option_c": "外国語は思考速度を遅くする",
        "option_d": "文法規則が自由な発想を妨げる",
        "correct_answer": "B",
        "explanation": "言語に該当する語彙がない概念は認識しにくいという点が「制限」の意味だと文章から読み取れる。",
        "source_url": "",
        "passage": "言語は単なる伝達の道具ではない。人が思考する際、言語はその枠組みそのものを形成する。ある概念を表す言葉が存在しない言語の話者は、その概念を認識しにくいという研究がある。例えば、色の区別を細かく持つ言語の話者は、そうでない言語の話者より色の識別が得意とされる。これは、言語が思考を助けるだけでなく、時に制限することも示している。",
    },
    {
        "level": "N1",
        "question_type": "reading",
        "question_text": "筆者の言語観として最も近いものはどれですか。",
        "option_a": "言語は中立的な道具である",
        "option_b": "言語は思考と密接に結びついている",
        "option_c": "言語の違いに優劣がある",
        "option_d": "言語より非言語的思考が重要だ",
        "correct_answer": "B",
        "explanation": "筆者は言語が思考の枠組みを形成するという立場で、両者の密接な関係を強調している。",
        "source_url": "",
        "passage": "言語は単なる伝達の道具ではない。人が思考する際、言語はその枠組みそのものを形成する。ある概念を表す言葉が存在しない言語の話者は、その概念を認識しにくいという研究がある。例えば、色の区別を細かく持つ言語の話者は、そうでない言語の話者より色の識別が得意とされる。これは、言語が思考を助けるだけでなく、時に制限することも示している。",
    },
    # Passage 2: Environmental policy (5 questions)
    {
        "level": "N1",
        "question_type": "reading",
        "question_text": "この文章で述べられている環境政策の課題は何ですか。",
        "option_a": "技術開発のコストが高すぎる",
        "option_b": "経済成長と環境保護の両立の難しさ",
        "option_c": "国際的な合意が得られない",
        "option_d": "市民の環境意識が低い",
        "correct_answer": "B",
        "explanation": "文章は経済発展を求める声と環境規制の間のジレンマを中心的な課題として論じている。",
        "source_url": "",
        "passage": "持続可能な社会の実現を目指す上で、環境政策は避けて通れない課題である。しかし、厳格な環境規制は産業活動を制約し、経済成長に悪影響を与えるという懸念が常につきまとう。先進国ではこのジレンマを技術革新によって解決しようとする試みが続いているが、途上国では経済発展を優先せざるを得ない状況もある。環境保護と経済成長を対立概念ではなく、相互補完的なものと捉え直す視点が今こそ必要とされている。",
    },
    {
        "level": "N1",
        "question_type": "reading",
        "question_text": "先進国はジレンマをどのように解決しようとしていますか。",
        "option_a": "環境規制を緩和することで",
        "option_b": "途上国に環境対策を任せることで",
        "option_c": "技術革新によって",
        "option_d": "経済成長を諦めることで",
        "correct_answer": "C",
        "explanation": "文章中に「技術革新によって解決しようとする試みが続いている」と明記されている。",
        "source_url": "",
        "passage": "持続可能な社会の実現を目指す上で、環境政策は避けて通れない課題である。しかし、厳格な環境規制は産業活動を制約し、経済成長に悪影響を与えるという懸念が常につきまとう。先進国ではこのジレンマを技術革新によって解決しようとする試みが続いているが、途上国では経済発展を優先せざるを得ない状況もある。環境保護と経済成長を対立概念ではなく、相互補完的なものと捉え直す視点が今こそ必要とされている。",
    },
    {
        "level": "N1",
        "question_type": "reading",
        "question_text": "筆者が最終的に提唱する視点はどれですか。",
        "option_a": "環境保護を経済成長より優先する",
        "option_b": "環境保護と経済成長を補い合うものとして捉える",
        "option_c": "経済成長を最優先にする",
        "option_d": "国際機関に判断を委ねる",
        "correct_answer": "B",
        "explanation": "筆者は「相互補完的なものと捉え直す視点が必要」と結論付けている。",
        "source_url": "",
        "passage": "持続可能な社会の実現を目指す上で、環境政策は避けて通れない課題である。しかし、厳格な環境規制は産業活動を制約し、経済成長に悪影響を与えるという懸念が常につきまとう。先進国ではこのジレンマを技術革新によって解決しようとする試みが続いているが、途上国では経済発展を優先せざるを得ない状況もある。環境保護と経済成長を対立概念ではなく、相互補完的なものと捉え直す視点が今こそ必要とされている。",
    },
    {
        "level": "N1",
        "question_type": "reading",
        "question_text": "途上国の状況について、筆者はどのように述べていますか。",
        "option_a": "環境規制を率先して導入している",
        "option_b": "経済発展を優先せざるを得ない面がある",
        "option_c": "技術革新で先進国をリードしている",
        "option_d": "国際的な支援を必要としていない",
        "correct_answer": "B",
        "explanation": "「途上国では経済発展を優先せざるを得ない状況もある」と文章に述べられている。",
        "source_url": "",
        "passage": "持続可能な社会の実現を目指す上で、環境政策は避けて通れない課題である。しかし、厳格な環境規制は産業活動を制約し、経済成長に悪影響を与えるという懸念が常につきまとう。先進国ではこのジレンマを技術革新によって解決しようとする試みが続いているが、途上国では経済発展を優先せざるを得ない状況もある。環境保護と経済成長を対立概念ではなく、相互補完的なものと捉え直す視点が今こそ必要とされている。",
    },
    {
        "level": "N1",
        "question_type": "reading",
        "question_text": "「対立概念ではなく」という表現が示す筆者の考えはどれですか。",
        "option_a": "環境と経済はどちらかを選ぶべきだ",
        "option_b": "環境と経済は共存できる",
        "option_c": "環境問題は経済問題より深刻だ",
        "option_d": "経済政策が環境問題を生んだ",
        "correct_answer": "B",
        "explanation": "対立ではなく補完関係として捉えるべきだという筆者の主張は、共存可能だという考えを示す。",
        "source_url": "",
        "passage": "持続可能な社会の実現を目指す上で、環境政策は避けて通れない課題である。しかし、厳格な環境規制は産業活動を制約し、経済成長に悪影響を与えるという懸念が常につきまとう。先進国ではこのジレンマを技術革新によって解決しようとする試みが続いているが、途上国では経済発展を優先せざるを得ない状況もある。環境保護と経済成長を対立概念ではなく、相互補完的なものと捉え直す視点が今こそ必要とされている。",
    },
]

N1_LISTENING = [
    {
        "level": "N1",
        "question_type": "listening",
        "question_text": "会話を聞いて、男性が提案していることは何ですか。",
        "option_a": "会議を延期する",
        "option_b": "オンラインで会議を行う",
        "option_c": "会議を中止する",
        "option_d": "別の参加者を呼ぶ",
        "correct_answer": "B",
        "explanation": "男性は移動コストと時間の節約のためオンライン会議を提案している。",
        "source_url": "",
        "passage": "男：来月の全国会議なんですが、わざわざ東京まで出向くのは時間もコストも大変ですよね。\n女：確かに。何か別の方法があればいいのですが。\n男：オンラインで開催するのはどうでしょうか。最近はシステムも整ってきましたし。\n女：それはいい案ですね。上司に相談してみます。",
    },
    {
        "level": "N1",
        "question_type": "listening",
        "question_text": "会話を聞いて、女性はなぜ困っていますか。",
        "option_a": "締め切りまで時間がない",
        "option_b": "資料が見つからない",
        "option_c": "上司に相談できない",
        "option_d": "パソコンが故障した",
        "correct_answer": "A",
        "explanation": "女性は報告書の締め切りが明日に迫っており、時間が足りないと述べている。",
        "source_url": "",
        "passage": "女：困ったわ。報告書の締め切りが明日なのに、まだ半分も終わっていないの。\n男：何か手伝えることはありますか？\n女：データの集計を手伝ってもらえると助かるんだけど。\n男：わかりました。すぐにやります。",
    },
    {
        "level": "N1",
        "question_type": "listening",
        "question_text": "会話を聞いて、二人が決めたことは何ですか。",
        "option_a": "新製品の発売を遅らせる",
        "option_b": "市場調査を追加で行う",
        "option_c": "予算を増やす",
        "option_d": "担当者を変更する",
        "correct_answer": "B",
        "explanation": "二人は既存データだけでは不十分として、追加の市場調査を実施することで合意した。",
        "source_url": "",
        "passage": "男：新製品の戦略を立てるには既存のデータだけでは不十分ではないでしょうか。\n女：おっしゃる通りです。ターゲット層の意見をもっと集める必要がありますね。\n男：では、追加で市場調査を実施することにしましょう。\n女：賛成です。来週中に計画を立てます。",
    },
    {
        "level": "N1",
        "question_type": "listening",
        "question_text": "講義を聞いて、教授が強調していることは何ですか。",
        "option_a": "暗記の重要性",
        "option_b": "批判的思考の重要性",
        "option_c": "グループワークの重要性",
        "option_d": "試験対策の重要性",
        "correct_answer": "B",
        "explanation": "教授は情報を鵜呑みにせず、批判的に分析する能力の重要性を強調している。",
        "source_url": "",
        "passage": "教授：現代社会では情報があふれています。重要なのは情報を受け取るだけでなく、その信頼性や論理性を批判的に評価する能力です。\n学生：情報を疑うということですか？\n教授：そうです。複数の視点から検討し、自分で考える習慣を身につけてください。",
    },
    {
        "level": "N1",
        "question_type": "listening",
        "question_text": "会話を聞いて、女性はどのような点を評価していますか。",
        "option_a": "価格が安いこと",
        "option_b": "デザインが優れていること",
        "option_c": "使いやすさ",
        "option_d": "耐久性の高さ",
        "correct_answer": "C",
        "explanation": "女性は操作が直感的でわかりやすい点を評価している。",
        "source_url": "",
        "passage": "女：この新しいアプリ、使ってみましたか？\n男：ええ、機能は多いけど少し複雑ですね。\n女：最初はそう思ったんですが、操作が直感的でわかりやすいんですよ。慣れるととても便利です。\n男：そうですか。もう少し試してみます。",
    },
    {
        "level": "N1",
        "question_type": "listening",
        "question_text": "ニュースを聞いて、報道の内容として正しいものはどれですか。",
        "option_a": "新しい条約が締結された",
        "option_b": "交渉が決裂した",
        "option_c": "両国が追加協議を行うことになった",
        "option_d": "制裁措置が発動された",
        "correct_answer": "C",
        "explanation": "ニュースでは両国の交渉が合意に至らず、追加協議を継続することが報じられた。",
        "source_url": "",
        "passage": "アナウンサー：本日の二国間交渉は合意に至らず、双方は引き続き協議を続けることで一致しました。次回の会合は来月初旬に予定されており、主要な懸案事項について再度話し合われる見込みです。",
    },
    {
        "level": "N1",
        "question_type": "listening",
        "question_text": "会話を聞いて、男性はなぜ転職を考えていますか。",
        "option_a": "給与が低いから",
        "option_b": "通勤が遠いから",
        "option_c": "自分のスキルを活かせていないから",
        "option_d": "職場の人間関係が悪いから",
        "correct_answer": "C",
        "explanation": "男性は現職では専門スキルを発揮できる機会が少ないと述べている。",
        "source_url": "",
        "passage": "男：最近、転職を真剣に考えているんです。\n女：えっ、何かあったんですか？\n男：今の職場では自分の専門スキルをなかなか活かせなくて。もっと専門性を伸ばせる環境に移りたいんです。\n女：なるほど。キャリアアップを考えているんですね。",
    },
    {
        "level": "N1",
        "question_type": "listening",
        "question_text": "会話を聞いて、二人が合意したこととして正しいものはどれですか。",
        "option_a": "イベントを中止する",
        "option_b": "イベントの規模を縮小する",
        "option_c": "イベントの日程を変更する",
        "option_d": "イベントを予定通り開催する",
        "correct_answer": "C",
        "explanation": "天候と会場の問題から、二人はイベントを別の日程に変更することに合意した。",
        "source_url": "",
        "passage": "女：来週のイベント、天気予報が雨なんですよね。屋外なので心配で。\n男：会場の屋根付きエリアは工事中で使えないし、困りましたね。\n女：いっそ日程を変更してはどうでしょう？再来週なら晴れの予報です。\n男：それがいいですね。参加者に連絡を取りましょう。",
    },
]


def get_n1_questions() -> list[dict]:
    return N1_VOCAB + N1_GRAMMAR + N1_READING + N1_LISTENING
